version: "3.7"

services:
  cloudKeeper:
    image: cloudkeeper-app:latest
    build: ./
    ports:
      - 8081:8081
    depends_on:
      - cloud-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cloud-db:5432/cloud_db
  cloudKeeper-frontend:
    image: cloudkeeper-frontend:latest
    ports:
      - 8080:8080
  cloud-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_DB: "cloud_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"