version: "3.7"

services:
  cloudKeeper:
    image: cloudkeeper-app:latest
    build: ./
    ports:
      - 8081:8081
  cloudKeeper-frontend:
    image: cloudkeeper-frontend:latest
      #environment:
      #PORT: 3000
    #PROXY_API: http://playground-web-backend:8080/
    ports:
      - 8080:8080
  cloud-db:
    image: charming_villani:latest
    environment:
      POSTGRES_DB: "cloud_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432