  server:
    port: 8081
  spring:
    datasource:
      url: 'jdbc:postgresql://localhost:5432/cloud_db'
      username: postgres
      password: postgres
    servlet:
      multipart:
        enabled: 'true'
        max-request-size: 215MB
        file-size-threshold: 2KB
        max-file-size: 500MB
      jpa:
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
              lob:
                non_contextual_creation: 'true'
        hibernate:
          ddl-auto: update
  app:
    jwt:
      secret: '$ecretKey'
      expirationMs: '86400000'
    configuration:
      cors:
        origins: 'http://localhost:8080'
        methods: '*'
        headers: '*'
        allow-credentials: true
      threadPoolTaskExecutor:
        corePoolSize: 50
        maxPoolSize: 50



